[package]
name = "nova"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
debug = []
verbose = ["debug"]

[dependencies]
byteorder = "1.5.0"
memuse = "0.2.1"
