[package]
name = "nova"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
debug = []
verbose = ["debug"]

[dependencies]
memuse = "0.2.1"
